from typing import Protocol, Optional, Sequence, Any, Iterable

from dkm_lib_db.db_types import DbConnInfo


class DbCursor(Protocol):
    def get_description(self) -> Optional[Sequence[Sequence[Any]]]: ...
    def get_rowcount(self) -> int: ...

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> Any: ...
    def __iter__(self) -> Iterable[Sequence[Any]]: ...
    def close(self) -> None: ...


class DbConn(Protocol):
    def cursor(self) -> DbCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def normalize_sql(self, sql:str) -> str: ...
    def set_autocommit(self, v:bool) -> None: ...

class DbDriver(Protocol):
    """
    Treiber-Adapter (pyodbc / mysqlclient / pymysql / …) kapseln hier drin:
    - connect()
    - placeholder/paramstyle mapping
    - cursor row mapping (dict rows)
    """
    def connect(self, conn_info:DbConnInfo) -> DbConn: ...
    #def convert_sql(self, sql: str) -> str: ...
    #def iter_query(self, conn: DbConn, sql: str, fn_on_row_found: OnRowFound, params: Sequence[Any]) -> None: ...
    #def exec_query(self, conn: DbConn, sql: str, params: Sequence[Any]) -> Any: ...
